// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Label label1;
    
    private Gtk.FileChooserButton filechooserbutton1;
    
    private Gtk.Button button5;
    
    private Gtk.Button button2;
    
    private Gtk.CheckButton checkbutton1;
    
    private Gtk.HPaned hpaned1;
    
    private Gtk.VBox vbox7;
    
    private Gtk.HBox hbox17;
    
    private Gtk.Label label5;
    
    private Gtk.HBox hbox18;
    
    private Gtk.ScrolledWindow GtkScrolledWindow3;
    
    private Gtk.TreeView treeview1;
    
    private Gtk.VBox vbox8;
    
    private Gtk.Button button1;
    
    private Gtk.Button button6;
    
    private Gtk.Button button7;
    
    private Gtk.Button button8;
    
    private Gtk.HSeparator hseparator1;
    
    private Gtk.Button button9;
    
    private Gtk.HSeparator hseparator2;
    
    private Gtk.HSeparator hseparator3;
    
    private Gtk.Button button10;
    
    private Gtk.VPaned vpaned2;
    
    private Gtk.VBox vbox4;
    
    private Gtk.HBox hbox12;
    
    private Gtk.ScrolledWindow GtkScrolledWindow2;
    
    private Gtk.TextView textview3;
    
    private Gtk.VPaned vpaned3;
    
    private Gtk.VBox vbox5;
    
    private Gtk.HBox hbox13;
    
    private Gtk.Label label3;
    
    private Gtk.Button button3;
    
    private Gtk.HBox hbox14;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.TextView textview1;
    
    private Gtk.VBox vbox6;
    
    private Gtk.HBox hbox15;
    
    private Gtk.Label label2;
    
    private Gtk.Button button4;
    
    private Gtk.HBox hbox16;
    
    private Gtk.ScrolledWindow GtkScrolledWindow1;
    
    private Gtk.TextView textview2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("File Name cleaner");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Directory : ");
        this.hbox1.Add(this.label1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        w1.Padding = ((uint)(6));
        // Container child hbox1.Gtk.Box+BoxChild
        this.filechooserbutton1 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Select A File"), ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton1.Name = "filechooserbutton1";
        this.hbox1.Add(this.filechooserbutton1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.filechooserbutton1]));
        w2.Position = 1;
        w2.Padding = ((uint)(6));
        // Container child hbox1.Gtk.Box+BoxChild
        this.button5 = new Gtk.Button();
        this.button5.CanFocus = true;
        this.button5.Name = "button5";
        this.button5.UseUnderline = true;
        this.button5.Label = Mono.Unix.Catalog.GetString("Clean filenames");
        this.hbox1.Add(this.button5);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.button5]));
        w3.PackType = ((Gtk.PackType)(1));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        w3.Padding = ((uint)(6));
        // Container child hbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Test clean ");
        this.hbox1.Add(this.button2);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.button2]));
        w4.PackType = ((Gtk.PackType)(1));
        w4.Position = 3;
        w4.Expand = false;
        w4.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.checkbutton1 = new Gtk.CheckButton();
        this.checkbutton1.CanFocus = true;
        this.checkbutton1.Name = "checkbutton1";
        this.checkbutton1.Label = Mono.Unix.Catalog.GetString("Recursive");
        this.checkbutton1.DrawIndicator = true;
        this.checkbutton1.UseUnderline = true;
        this.hbox1.Add(this.checkbutton1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.checkbutton1]));
        w5.PackType = ((Gtk.PackType)(1));
        w5.Position = 4;
        w5.Expand = false;
        w5.Padding = ((uint)(6));
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w6.Position = 0;
        w6.Expand = false;
        w6.Fill = false;
        w6.Padding = ((uint)(6));
        // Container child vbox1.Gtk.Box+BoxChild
        this.hpaned1 = new Gtk.HPaned();
        this.hpaned1.CanFocus = true;
        this.hpaned1.Name = "hpaned1";
        this.hpaned1.Position = 363;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.vbox7 = new Gtk.VBox();
        this.vbox7.Name = "vbox7";
        this.vbox7.Spacing = 6;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox17 = new Gtk.HBox();
        this.hbox17.Name = "hbox17";
        this.hbox17.Spacing = 6;
        // Container child hbox17.Gtk.Box+BoxChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Remove these, spaces can be essential, also accepts regex");
        this.hbox17.Add(this.label5);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox17[this.label5]));
        w7.Position = 0;
        w7.Expand = false;
        w7.Fill = false;
        w7.Padding = ((uint)(6));
        this.vbox7.Add(this.hbox17);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox17]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox18 = new Gtk.HBox();
        this.hbox18.Name = "hbox18";
        this.hbox18.Spacing = 6;
        // Container child hbox18.Gtk.Box+BoxChild
        this.GtkScrolledWindow3 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
        this.GtkScrolledWindow3.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
        this.treeview1 = new Gtk.TreeView();
        this.treeview1.CanFocus = true;
        this.treeview1.Name = "treeview1";
        this.GtkScrolledWindow3.Add(this.treeview1);
        this.hbox18.Add(this.GtkScrolledWindow3);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox18[this.GtkScrolledWindow3]));
        w10.Position = 0;
        w10.Padding = ((uint)(6));
        // Container child hbox18.Gtk.Box+BoxChild
        this.vbox8 = new Gtk.VBox();
        this.vbox8.Name = "vbox8";
        this.vbox8.Spacing = 6;
        // Container child vbox8.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        // Container child button1.Gtk.Container+ContainerChild
        Gtk.Alignment w11 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w12 = new Gtk.HBox();
        w12.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w13 = new Gtk.Image();
        w13.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-goto-top", Gtk.IconSize.Menu, 16);
        w12.Add(w13);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w15 = new Gtk.Label();
        w12.Add(w15);
        w11.Add(w12);
        this.button1.Add(w11);
        this.vbox8.Add(this.button1);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox8[this.button1]));
        w19.Position = 0;
        w19.Expand = false;
        w19.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.button6 = new Gtk.Button();
        this.button6.CanFocus = true;
        this.button6.Name = "button6";
        this.button6.UseUnderline = true;
        // Container child button6.Gtk.Container+ContainerChild
        Gtk.Alignment w20 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w21 = new Gtk.HBox();
        w21.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w22 = new Gtk.Image();
        w22.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-up", Gtk.IconSize.Menu, 16);
        w21.Add(w22);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w24 = new Gtk.Label();
        w21.Add(w24);
        w20.Add(w21);
        this.button6.Add(w20);
        this.vbox8.Add(this.button6);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox8[this.button6]));
        w28.Position = 1;
        w28.Expand = false;
        w28.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.button7 = new Gtk.Button();
        this.button7.CanFocus = true;
        this.button7.Name = "button7";
        this.button7.UseUnderline = true;
        // Container child button7.Gtk.Container+ContainerChild
        Gtk.Alignment w29 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w30 = new Gtk.HBox();
        w30.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w31 = new Gtk.Image();
        w31.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-down", Gtk.IconSize.Menu, 16);
        w30.Add(w31);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w33 = new Gtk.Label();
        w30.Add(w33);
        w29.Add(w30);
        this.button7.Add(w29);
        this.vbox8.Add(this.button7);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox8[this.button7]));
        w37.Position = 2;
        w37.Expand = false;
        w37.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.button8 = new Gtk.Button();
        this.button8.CanFocus = true;
        this.button8.Name = "button8";
        this.button8.UseUnderline = true;
        // Container child button8.Gtk.Container+ContainerChild
        Gtk.Alignment w38 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w39 = new Gtk.HBox();
        w39.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w40 = new Gtk.Image();
        w40.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-goto-bottom", Gtk.IconSize.Menu, 16);
        w39.Add(w40);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w42 = new Gtk.Label();
        w39.Add(w42);
        w38.Add(w39);
        this.button8.Add(w38);
        this.vbox8.Add(this.button8);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.vbox8[this.button8]));
        w46.Position = 3;
        w46.Expand = false;
        w46.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.hseparator1 = new Gtk.HSeparator();
        this.hseparator1.Name = "hseparator1";
        this.vbox8.Add(this.hseparator1);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.vbox8[this.hseparator1]));
        w47.Position = 4;
        w47.Expand = false;
        w47.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.button9 = new Gtk.Button();
        this.button9.CanFocus = true;
        this.button9.Name = "button9";
        this.button9.UseUnderline = true;
        // Container child button9.Gtk.Container+ContainerChild
        Gtk.Alignment w48 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w49 = new Gtk.HBox();
        w49.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w50 = new Gtk.Image();
        w50.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
        w49.Add(w50);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w52 = new Gtk.Label();
        w49.Add(w52);
        w48.Add(w49);
        this.button9.Add(w48);
        this.vbox8.Add(this.button9);
        Gtk.Box.BoxChild w56 = ((Gtk.Box.BoxChild)(this.vbox8[this.button9]));
        w56.Position = 5;
        w56.Expand = false;
        w56.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.hseparator2 = new Gtk.HSeparator();
        this.hseparator2.Name = "hseparator2";
        this.vbox8.Add(this.hseparator2);
        Gtk.Box.BoxChild w57 = ((Gtk.Box.BoxChild)(this.vbox8[this.hseparator2]));
        w57.Position = 6;
        w57.Expand = false;
        w57.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.hseparator3 = new Gtk.HSeparator();
        this.hseparator3.Name = "hseparator3";
        this.vbox8.Add(this.hseparator3);
        Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.vbox8[this.hseparator3]));
        w58.Position = 7;
        w58.Expand = false;
        w58.Fill = false;
        // Container child vbox8.Gtk.Box+BoxChild
        this.button10 = new Gtk.Button();
        this.button10.CanFocus = true;
        this.button10.Name = "button10";
        this.button10.UseUnderline = true;
        // Container child button10.Gtk.Container+ContainerChild
        Gtk.Alignment w59 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w60 = new Gtk.HBox();
        w60.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w61 = new Gtk.Image();
        w61.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
        w60.Add(w61);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w63 = new Gtk.Label();
        w60.Add(w63);
        w59.Add(w60);
        this.button10.Add(w59);
        this.vbox8.Add(this.button10);
        Gtk.Box.BoxChild w67 = ((Gtk.Box.BoxChild)(this.vbox8[this.button10]));
        w67.Position = 8;
        w67.Expand = false;
        w67.Fill = false;
        this.hbox18.Add(this.vbox8);
        Gtk.Box.BoxChild w68 = ((Gtk.Box.BoxChild)(this.hbox18[this.vbox8]));
        w68.Position = 1;
        w68.Expand = false;
        w68.Fill = false;
        this.vbox7.Add(this.hbox18);
        Gtk.Box.BoxChild w69 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox18]));
        w69.Position = 1;
        w69.Padding = ((uint)(6));
        this.hpaned1.Add(this.vbox7);
        Gtk.Paned.PanedChild w70 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vbox7]));
        w70.Resize = false;
        // Container child hpaned1.Gtk.Paned+PanedChild
        this.vpaned2 = new Gtk.VPaned();
        this.vpaned2.CanFocus = true;
        this.vpaned2.Name = "vpaned2";
        this.vpaned2.Position = 125;
        // Container child vpaned2.Gtk.Paned+PanedChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox12 = new Gtk.HBox();
        this.hbox12.Name = "hbox12";
        this.hbox12.Spacing = 6;
        // Container child hbox12.Gtk.Box+BoxChild
        this.GtkScrolledWindow2 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow2.WidthRequest = 500;
        this.GtkScrolledWindow2.HeightRequest = 60;
        this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
        this.GtkScrolledWindow2.HscrollbarPolicy = ((Gtk.PolicyType)(2));
        this.GtkScrolledWindow2.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
        this.textview3 = new Gtk.TextView();
        this.textview3.CanFocus = true;
        this.textview3.Name = "textview3";
        this.textview3.WrapMode = ((Gtk.WrapMode)(1));
        this.GtkScrolledWindow2.Add(this.textview3);
        this.hbox12.Add(this.GtkScrolledWindow2);
        Gtk.Box.BoxChild w72 = ((Gtk.Box.BoxChild)(this.hbox12[this.GtkScrolledWindow2]));
        w72.Position = 0;
        w72.Padding = ((uint)(6));
        this.vbox4.Add(this.hbox12);
        Gtk.Box.BoxChild w73 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox12]));
        w73.Position = 0;
        w73.Padding = ((uint)(6));
        this.vpaned2.Add(this.vbox4);
        Gtk.Paned.PanedChild w74 = ((Gtk.Paned.PanedChild)(this.vpaned2[this.vbox4]));
        w74.Resize = false;
        // Container child vpaned2.Gtk.Paned+PanedChild
        this.vpaned3 = new Gtk.VPaned();
        this.vpaned3.CanFocus = true;
        this.vpaned3.Name = "vpaned3";
        this.vpaned3.Position = 187;
        // Container child vpaned3.Gtk.Paned+PanedChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox13 = new Gtk.HBox();
        this.hbox13.Name = "hbox13";
        this.hbox13.Spacing = 6;
        // Container child hbox13.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Cleaned");
        this.hbox13.Add(this.label3);
        Gtk.Box.BoxChild w75 = ((Gtk.Box.BoxChild)(this.hbox13[this.label3]));
        w75.Position = 0;
        w75.Expand = false;
        w75.Fill = false;
        w75.Padding = ((uint)(6));
        // Container child hbox13.Gtk.Box+BoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Clear");
        this.hbox13.Add(this.button3);
        Gtk.Box.BoxChild w76 = ((Gtk.Box.BoxChild)(this.hbox13[this.button3]));
        w76.PackType = ((Gtk.PackType)(1));
        w76.Position = 2;
        w76.Expand = false;
        w76.Fill = false;
        w76.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox13);
        Gtk.Box.BoxChild w77 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox13]));
        w77.Position = 0;
        w77.Expand = false;
        w77.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox14 = new Gtk.HBox();
        this.hbox14.Name = "hbox14";
        this.hbox14.Spacing = 6;
        // Container child hbox14.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.textview1 = new Gtk.TextView();
        this.textview1.CanFocus = true;
        this.textview1.Name = "textview1";
        this.GtkScrolledWindow.Add(this.textview1);
        this.hbox14.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w79 = ((Gtk.Box.BoxChild)(this.hbox14[this.GtkScrolledWindow]));
        w79.Position = 0;
        w79.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox14);
        Gtk.Box.BoxChild w80 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox14]));
        w80.Position = 1;
        w80.Padding = ((uint)(6));
        this.vpaned3.Add(this.vbox5);
        Gtk.Paned.PanedChild w81 = ((Gtk.Paned.PanedChild)(this.vpaned3[this.vbox5]));
        w81.Resize = false;
        // Container child vpaned3.Gtk.Paned+PanedChild
        this.vbox6 = new Gtk.VBox();
        this.vbox6.Name = "vbox6";
        this.vbox6.Spacing = 6;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox15 = new Gtk.HBox();
        this.hbox15.Name = "hbox15";
        this.hbox15.Spacing = 6;
        // Container child hbox15.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Errors");
        this.hbox15.Add(this.label2);
        Gtk.Box.BoxChild w82 = ((Gtk.Box.BoxChild)(this.hbox15[this.label2]));
        w82.Position = 0;
        w82.Expand = false;
        w82.Fill = false;
        w82.Padding = ((uint)(6));
        // Container child hbox15.Gtk.Box+BoxChild
        this.button4 = new Gtk.Button();
        this.button4.CanFocus = true;
        this.button4.Name = "button4";
        this.button4.UseUnderline = true;
        this.button4.Label = Mono.Unix.Catalog.GetString("Clear");
        this.hbox15.Add(this.button4);
        Gtk.Box.BoxChild w83 = ((Gtk.Box.BoxChild)(this.hbox15[this.button4]));
        w83.PackType = ((Gtk.PackType)(1));
        w83.Position = 2;
        w83.Expand = false;
        w83.Fill = false;
        w83.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox15);
        Gtk.Box.BoxChild w84 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox15]));
        w84.Position = 0;
        w84.Expand = false;
        w84.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox16 = new Gtk.HBox();
        this.hbox16.Name = "hbox16";
        this.hbox16.Spacing = 6;
        // Container child hbox16.Gtk.Box+BoxChild
        this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.textview2 = new Gtk.TextView();
        this.textview2.CanFocus = true;
        this.textview2.Name = "textview2";
        this.GtkScrolledWindow1.Add(this.textview2);
        this.hbox16.Add(this.GtkScrolledWindow1);
        Gtk.Box.BoxChild w86 = ((Gtk.Box.BoxChild)(this.hbox16[this.GtkScrolledWindow1]));
        w86.Position = 0;
        w86.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox16);
        Gtk.Box.BoxChild w87 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox16]));
        w87.Position = 1;
        w87.Padding = ((uint)(6));
        this.vpaned3.Add(this.vbox6);
        this.vpaned2.Add(this.vpaned3);
        this.hpaned1.Add(this.vpaned2);
        this.vbox1.Add(this.hpaned1);
        Gtk.Box.BoxChild w91 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
        w91.Position = 1;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 877;
        this.DefaultHeight = 535;
        this.Show();
        this.DestroyEvent += new Gtk.DestroyEventHandler(this.OnDestroyEvent);
        this.button2.Clicked += new System.EventHandler(this.OnRunClicked);
        this.button5.Clicked += new System.EventHandler(this.OnRunClicked);
        this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
        this.button4.Clicked += new System.EventHandler(this.OnButton4Clicked);
    }
}
